update docker-compose

diff --git a/bin/docker-compose b/bin/docker-compose
--- a/bin/docker-compose
+++ b/bin/docker-compose
@@ -1,13 +1,14 @@
 #!/bin/bash -e
 
 DOCKER_COMPOSE_DIR="$(dirname $(realpath "${BASH_SOURCE[0]}"))"
-DOCKER_COMPOSE_VERSION="1.25.0"
+DOCKER_COMPOSE_VERSION="1.25.3"
 DOCKER_COMPOSE_ARCH="$(uname -s)-$(uname -m)"
 DOCKER_COMPOSE_URL="https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$DOCKER_COMPOSE_ARCH"
 DOCKER_COMPOSE_NAME="docker-compose-$DOCKER_COMPOSE_VERSION-$DOCKER_COMPOSE_ARCH"
 
 if [ ! -f "$DOCKER_COMPOSE_DIR/$DOCKER_COMPOSE_NAME" ]; then
-    curl -L "$DOCKER_COMPOSE_URL" -o "$DOCKER_COMPOSE_DIR/$DOCKER_COMPOSE_NAME"
+    echo "Fetching docker-compose version $DOCKER_COMPOSE_VERSION ..."
+    curl -f -L "$DOCKER_COMPOSE_URL" -o "$DOCKER_COMPOSE_DIR/$DOCKER_COMPOSE_NAME" || (echo "Could not download docker-compose from $DOCKER_COMPOSE_URL." >&2; exit 1)
     chmod +x "$DOCKER_COMPOSE_DIR/$DOCKER_COMPOSE_NAME"
 fi
 
